### ISSUE TITLE
SyntaxError: 'return' outside function

### ISSUE THREAD

**Issue by Kraypex** [djlorenzouasset/Cosmetics-Generator#4] opened 2023-02-12 10:15 UTC
utils/error.py

**Comment by djlorenzouasset** [comment] 2023-02-12 13:27
Thank u, the issue is now fixed: https://github.com/djlorenzouasset/Cosmetics-Generator/commit/a3288a5dc16eac8955c0baee329e89c7657cc9d9

**Closed by djlorenzouasset** 2023-02-12 13:27 UTC
